# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4804c46094ff1a43f41df6eeda01757c02ffe2c4f4c87b32de114499a8d33380590483402773490ab9faa95ffbd381e2cde8b4fd2ddb7b53f46de29a527f4216

test:
  secret_key_base: 71a98b2ae1c3886fe597595923744526aa3f462ca8c036d92464bb6bc632cd6ba404a0b301f1e10393528aa6379169d9d461d33ed7dbadea826721874d57679d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
